### ISSUE TITLE
fastnetmon is crashing when detecting attack

### ISSUE THREAD

**Issue by mihailtudoran** [FastVPSEestiOu/fastnetmon#241] opened 2015-06-02 10:44 UTC
Hello Fastnetmon,

In order for me to do some tests I run fastnetmon with e1000e driver patched with netmap and set a threshold of 1000 pps, after a attack is detected fastnetmon crashes with segfaul.

dmesg output:
[79731.203770] fastnetmon[25229]: segfault at 1b549a0 ip 000000000042c4bb sp 00007ff98603ec50 error 6 in fastnetmon[400000+91000]

fastnetmon.log output:
2015-06-02 12:32:27,818 [INFO] We start total zerofication of counters
2015-06-02 12:32:27,819 [INFO] We finished zerofication
2015-06-02 12:32:27,819 [INFO] We loaded 14 subnets to our in-memory list of networks
2015-06-02 12:32:27,819 [INFO] Total number of monitored hosts (total size of all networks): 3841
2015-06-02 12:32:27,819 [INFO] Run banlist cleanup thread
2015-06-02 12:32:27,819 [INFO] Netmap plugin started
2015-06-02 12:32:27,819 [INFO] netmap will listen on 1 interfaces
2015-06-02 12:32:27,819 [INFO] netmap will sniff interface: eth2
2015-06-02 12:32:27,819 [INFO] netflow plugin started
2015-06-02 12:32:27,819 [INFO] We use custom sampling ratio for netflow: 1
2015-06-02 12:32:27,819 [INFO] netflow plugin will listen on 127.0.0.1:2055 udp port
2015-06-02 12:32:27,819 [INFO] We have 2 cpus
2015-06-02 12:32:28,002 [INFO] Mapped 334980KB memory at 0x7ff95b8df000
2015-06-02 12:32:28,002 [INFO] We have 1 tx and 1 rx rings
2015-06-02 12:32:28,002 [INFO] We have number of CPUs bigger than number of NIC RX queues. Set number of CPU's to number of threads
2015-06-02 12:32:28,002 [INFO] Wait 2 seconds for NIC reset
2015-06-02 12:32:30,004 [INFO] My first ring is 0 and last ring id is 0 I'm thread 0
2015-06-02 12:32:30,004 [INFO] Start new netmap thread 0
2015-06-02 12:32:30,004 [INFO] I will bind this thread to logical CPU: 0
2015-06-02 12:32:32,832 [INFO] We run execute_ip_ban code with following params in_pps: 1012 out_pps: 0 in_bps: 1428844 out_bps: 0 and we decide it's incoming attack
2015-06-02 12:32:32,832 [INFO] Attack with direction: incoming IP: xxxxxxxxx Power: 1012
2015-06-02 12:32:32,833 [INFO] Call script for ban client: xxxxxxxxxxxxxxxx
2015-06-02 12:32:32,833 [INFO] Script for ban client is finished: xxxxxxxxxxxxx
2015-06-02 12:32:33,418 [INFO] Attack with direction: incoming IP: xxxxxxxxxxxx Power: 1012 traffic sample collected
2015-06-02 12:32:33,419 [INFO] Call script for notify about attack details for: xxxxxxxxxxxx
2015-06-02 12:32:33,419 [INFO] Script for notify about attack details is finished: xxxxxxxxxxxx
2015-06-02 12:32:33,423 [ERROR] Sorry but we experienced error with popen. Please check your scripts. It should receive data on stdin!

Not very sure why but I think is has something to do with the notify script, in my case:
cat /usr/local/bin/notify_about_attack.sh 
```bash
#!/usr/bin/env bash

# $1 client_ip_as_string
# $2 data_direction
# $3 pps_as_string
# $4 action (ban or unban)

echo $1 $2 $3 $4
exit 0
```

You've done a really great job with this utility !

**Comment by pavel-odintsov** [comment] 2015-06-02 11:11
Hello!

It's not a bug :) As mentioned here: "Sorry but we experienced error with popen. Please check your scripts. It should receive data on stdin!".

You should read data from stdin of this script because FastNetMon pass details this way.

**Comment by pavel-odintsov** [comment] 2015-06-02 11:17
Please try this way:
```bash
cat /usr/local/bin/notify_about_attack.sh 
```bash
#!/usr/bin/env bash

# $1 client_ip_as_string
# $2 data_direction
# $3 pps_as_string
# $4 action (ban or unban)

# Receive stdin data and drop it away
cat > /dev/null

echo $1 $2 $3 $4
exit 0
```

**Comment by mihailtudoran** [comment] 2015-06-02 11:33
Thanks Pavel!

My bad... sorry.

Now it seems to work great, but it doesn't call the script to unban an IP, I only get:

root@ddos:/opt/fastnetmon/src/build# fastnetmon
xxxxxxxxxxxxxxxx incoming 2146 attack_details
xxxxxxxxxxxxxxxx incoming 2146 ban

On fastnetmon.log:

2015-06-02 13:28:33,543 [INFO] Start new netmap thread 0
2015-06-02 13:28:33,543 [INFO] I will bind this thread to logical CPU: 0
2015-06-02 13:28:53,436 [INFO] We run execute_ip_ban code with following params in_pps: 2146 out_pps: 0 in_bps: 3248716 out_bps: 0 and we decide it's incoming attack
2015-06-02 13:28:53,436 [INFO] Attack with direction: incoming IP: 93.114.160.104 Power: 2146
2015-06-02 13:28:53,436 [INFO] Call script for ban client: 93.114.160.104
2015-06-02 13:28:53,436 [INFO] Script for ban client is finished: 93.114.160.104
2015-06-02 13:28:54,219 [INFO] Attack with direction: incoming IP: 93.114.160.104 Power: 2146 traffic sample collected
2015-06-02 13:28:54,219 [INFO] Call script for notify about attack details for: 93.114.160.104
2015-06-02 13:28:54,219 [INFO] Script for notify about attack details is finished: 93.114.160.104
2015-06-02 13:30:01,349 [INFO] We will unban banned IP: 93.114.160.104 because it ban time 60 seconds is ended
2015-06-02 13:30:01,349 [INFO] Call script for unban client: 93.114.160.104
2015-06-02 13:30:01,349 [INFO] Script for unban client is finished: 93.114.160.104


From docs I understand the same script is called for ban/unban with $4 param changed according to action.

**Comment by pavel-odintsov** [comment] 2015-06-02 11:35
For unban you do not need read anything from stdin.

Please add work around for it:
```bash
if [ "$4" = "unban" ]; then
    # Unban actions if used
    exit 0
fi
```

**Comment by mihailtudoran** [comment] 2015-06-02 11:45
I don't see the print or the log written.
Wouldn't the echo at the bottom print the unban command anyway ?

This is my notify script:
<code>
#!/usr/bin/env bash

# $1 client_ip_as_string
# $2 data_direction
# $3 pps_as_string
# $4 action (ban or unban)

# Receive stdin data and drop it away

if [ "$4" = "unban" ]; then
    # Unban actions if used
    echo unban $1
    echo unbanned $1 > /usr/local/bin/logs
    exit 0
fi


cat > /dev/null

echo $1 $2 $3 $4
exit 0
</code>

Thanks!

**Comment by pavel-odintsov** [comment] 2015-06-02 12:47
I have no idea how it possible. For completely clear test could you try my https://github.com/FastVPSEestiOu/fastnetmon/blob/master/src/notify_about_attack.sh notify script example?

**Comment by mihailtudoran** [comment] 2015-06-02 12:56
I will try that.

This is strange because I see the thread init in fastnetmon.log:
2015-06-02 14:40:30,272 [INFO] Run banlist cleanup thread

But never see any "We will unban banned IP * " message after timeout expires and the banned IP still remains in the list inside fastnetmon_client after timeout expires.

Thanks !

**Comment by pavel-odintsov** [comment] 2015-06-02 15:38
What ban timeout do you use?

**Comment by mihailtudoran** [comment] 2015-06-02 19:55
Hi Pavel,

During the lab tests I used 60 seconds, now it seems to work. It might was something with my environment.

Another thing I noticed is if two or more IP get banned very fast ( one right after another ) fastnetmon will exit with segfault because of [ERROR] Sorry but we experienced error with popen. Please check your scripts. It should receive data on stdin!
Inside my script I call the vtysh from quagga to insert a /32 network and announce to my test router.

Output here:

```
2015-06-02 22:42:35,674 [INFO] We run execute_ip_ban code with following params in_pps: 2315 out_pps: 0 in_bps: 2929140 out_bps: 0 and we decide it's incoming attack
2015-06-02 22:42:35,674 [INFO] Attack with direction: incoming IP: xxxxxxxxxxx.80 Power: 2315
2015-06-02 22:42:35,674 [INFO] Call script for ban client: xxxxxxxxxxx.80
2015-06-02 22:42:35,674 [INFO] Script for ban client is finished: xxxxxxxxxxxx.80
2015-06-02 22:42:36,315 [INFO] Attack with direction: incoming IP: xxxxxxxxxx80 Power: 2315 traffic sample collected
2015-06-02 22:42:36,315 [INFO] Call script for notify about attack details for: xxxxxxxxxx.80
2015-06-02 22:42:36,315 [INFO] Script for notify about attack details is finished: xxxxxxxxx.80
2015-06-02 22:42:43,708 [INFO] We run execute_ip_ban code with following params in_pps: 2059 out_pps: 0 in_bps: 2745566 out_bps: 0 and we decide it's incoming attack
2015-06-02 22:42:43,708 [INFO] Attack with direction: incoming IP: xxxxxxxxxxxxxxx.36 Power: 2059
2015-06-02 22:42:43,708 [INFO] Call script for ban client: xxxxxxxxxxxxxx.36
2015-06-02 22:42:43,708 [INFO] Script for ban client is finished:xxxxxxxxxxxx.36
2015-06-02 22:42:44,496 [INFO] Attack with direction: incoming IP:xxxxxxxxxxxx.36 Power: 2059 traffic sample collected
2015-06-02 22:42:44,497 [INFO] Call script for notify about attack details for: xxxxxxxxxxxxxx.36
2015-06-02 22:42:44,497 [INFO] Script for notify about attack details is finished: xxxxxxxxxxxx.36
2015-06-02 22:43:18,826 [INFO] We run execute_ip_ban code with following params in_pps: 2251 out_pps: 0 in_bps: 3407916 out_bps: 0 and we decide it's incoming attack
2015-06-02 22:43:18,826 [INFO] Attack with direction: incoming IP: xxxxxxxxxxxxxx.104 Power: 2251
2015-06-02 22:43:18,826 [INFO] Call script for ban client: xxxxxxxxxxxxx.104
2015-06-02 22:43:18,826 [INFO] Script for ban client is finished: xxxxxxxxxxxx.104
2015-06-02 22:43:18,831 [ERROR] Sorry but we experienced error with popen. Please check your scripts. It should receive data on stdin!
```


Wouldn't be a good ideea to replace the exit() with a warning in case of popen error ?

Thanks!

**Comment by pavel-odintsov** [comment] 2015-06-03 11:08
Hello!

Thanks for deep testing of my toolkit. It's really helpful.

"Another thing I noticed is if two or more IP get banned very fast ( one right after another ) fastnetmon will exit with segfault because" - I need check it.

Really nice idea. I have disabled exit in case of popen error: https://github.com/FastVPSEestiOu/fastnetmon/commit/22cd49a4886a7e5dbc1ac9b00c5b1565333b5e16

Please do git pull and recompile code. 

But issue with broken popen only for two closer blocks is real bug. But I haven't idea how it possible.

**Comment by pavel-odintsov** [comment] 2015-06-03 11:09
I have created new issue about this bug: https://github.com/FastVPSEestiOu/fastnetmon/issues/246

**Comment by pavel-odintsov** [comment] 2015-06-03 11:09
Please try new code.

**Comment by mihailtudoran** [comment] 2015-06-08 10:57
Hello,

Tested a couple of days, looks good. Thanks!

**Comment by pavel-odintsov** [comment] 2015-06-08 12:23
Hello!

In new Git version you could specify config flag:
```bash
notify_script_pass_details = no
```

Which disables passing any details over stdin to notify script.

**Comment by pavel-odintsov** [comment] 2015-06-12 11:40
Hello!

Could you check another issue mentioned here and check it again: https://github.com/FastVPSEestiOu/fastnetmon/issues/246 ?

**Comment by pavel-odintsov** [comment] 2015-06-14 19:16
Thus, issue solved and I close this ticket. Still waiting for details in #246 :)

**Closed by pavel-odintsov** 2015-06-14 19:16 UTC
